os: linux
dist: trusty
sudo: false
language: php
php:
  - 7.2
services:
  - mysql
before_install:
  - pecl install mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'create database project_foodie;'
install:
  - cp .env.test .env
  - composer install
  - npm install
  - php artisan key:generate
  - php artisan migrate:fresh --seed
script:
  - php vendor/bin/phpcs ./
  - php vendor/bin/phpunit
