os: linux
dist: trusty
sudo: false
language: php
php:
  - 7.2
services:
  - mysql
  - mongodb
before_install:
  - pecl install mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install
  - npm install
  - cp .env.example .env
  - php artisan key:generate
  - mysql -e 'create database project_foodie;'
  - php artisan migrate:fresh --seed
script:
  - php vendor/bin/phpcs ./
  - php vendor/bin/phpunit
